### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by rufattabaev** [rufattabaev/webapp#1]
Требуется помощь. Всё сделал как на видео, но:
1. При запуске приложения в браузере вылетает error 404
2. Не понимаю в чем ошибка сборки на travis-ci

**Comment by coursar** [comment]
Внимательнее смотрите логи:
```
      [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project web-app: Fatal error compiling: invalid target release: 11 -> [Help 1]
```

Потому что в system.properties:
```
java.runtyme.version=11
```

А должно быть `runtime`.
