### ISSUE TITLE
Поправить внешний вид и разобраться с кодировкой

### ISSUE THREAD

**Issue by coursar** [rufattabaev/webapp#4]
<img width="506" alt="Снимок экрана 2019-11-14 в 14 10 18" src="https://user-images.githubusercontent.com/3601892/68852273-9d551680-06e8-11ea-9276-c8d099de8d75.png">

**Comment by rufattabaev** [comment]
Внешний вид поправил, а что не так с кодировкой не могу понять. В моём браузере вроде всё корректно отображается. В чем может быть причина?

**Comment by rufattabaev** [comment]
Проверял так же на Opera тоже всё корректно

**Comment by coursar** [comment]
Русский не отрабатывает (см. для объекта HttServletRequest как можно выставить кодировку - по умолчанию она ISO..., а не UTF-8)
